[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  bblanchon/ArduinoJson @ ^7.1.0
  arduino-libraries/ArduinoHttpClient @ ^0.6.1
